### ISSUE TITLE
TypeScript compile error (branch master)

### ISSUE THREAD

**Issue by Sin333** [tradingview/charting-library-tutorial#10]
![image](https://user-images.githubusercontent.com/16017825/88032506-b602af80-cb46-11ea-92bf-18f77b68bb94.png)

**Comment by Sin333** [comment]
Hi I give your library and try compile in angular 9 application, but I got some bugs. You can help me?

**Comment by timocov** [comment]
How this issue is related to this repo?

**Comment by Sin333** [comment]
sorry
