### ISSUE TITLE
Question about web content accessibility

### ISSUE THREAD

**Issue by npt05** [tradingview/charting-library-tutorial#119]
Before that my clients couldn't load chart.
But after she folow this step in IOS she can see chart
Settings > Screen Time > Content & Privacy Restrictions > Store, Web, Siri & Game Center Content > Web Content : change the **Web Content** to **Unrestricted**

Can you explain this to me?

My advanced chartLibrary Version: 23.024

**Comment by romfrancois** [comment]
Thanks for reporting.
Before I check with both the mobile and accessibility teams would you mind checking with a more recent version of the library. 
We've done some work on accessibility that was not in the version you specified so best to be on the latest.
