### ISSUE TITLE
RealTime bar

### ISSUE THREAD

**Issue by viditrysatria** [tradingview/charting-library-tutorial#120]
thiis is my console log for subscribe bar
![Screenshot 2024-07-17 143612](https://github.com/user-attachments/assets/3a0263dd-1848-4b80-8d71-a87297b94fc6)
in my streaming.js 
```if (tradeTime >= nextDailyBarTime) {
      bar = {
        time: nextDailyBarTime,
        open: o,
        high: h,
        low: l,
        close: tradePrice,
      };
      console.log("[socket] Generate new bar", bar);

      // subscriptionItem.lastDailyBar = bar;
      // subscriptionItem.handlers.forEach((handler) =>{
      //   console.log(handler);
      //   handler.reset()
      // });
      console.log("aq 1",lastDailyBar.time>= nextDailyBarTime)
      console.log("x 2",lastDailyBar.time< nextDailyBarTime)



    } else {
      bar = {
        ...lastDailyBar,
        high: Math.max(lastDailyBar.high, tradePrice),
        low: Math.min(lastDailyBar.low, tradePrice),
        close: tradePrice,
      };
      console.log("[socket] Update the latest bar by price", tradePrice);
      console.log("time", formatDate(new Date(t[0])))

    }
    subscriptionItem.lastDailyBar = bar;
    subscriptionItem.handlers.forEach((handler) =>{
      console.log("sss time",handler);
      console.log("sss bar",bar);
      handler.callback(bar)
    });
  };```
  i want my bar update after different time but itsnot update and my time alreadye more bigger in this log, can u help me how to set another bar in 5m intraday
 this is looks like in my chart after not update
 
![image](https://github.com/user-attachments/assets/8ff43492-207c-4b96-bfca-dfd17291e7f0)

**Comment by romfrancois** [comment]
Not quite sure I fully understand what the issue is here but if you follow both the tutorial from beginning to end + read the documentation for creating the [datafeed](https://www.tradingview.com/charting-library-docs/latest/connecting_data/Datafeed-API) you should have something working.

I would suggest sticking to making the tutorial working first and then changing it to fit your requirement.

**Comment by viditrysatria** [comment]
Hi Ron,
 
I have a problem with generating new bar/candle. 
![image](https://github.com/user-attachments/assets/a5f6a692-fa8f-49e0-860d-875e7556f739)
in the attachment, it said that it can create new bar. Is it the same method for update and generate a new bar because in my code is not generating a new bar.
this is my code for subscribebar. It is quite similar with the tutorial, the different is only for method "getNextDailyBarTime" because i want to add bar every 5 minute. In the tutorial it only add daily bar.
[code.txt](https://github.com/user-attachments/files/16276777/code.txt)
 
I also add recording video that shows the issue for creating new bar.
 https://github.com/user-attachments/assets/dbc1ac9a-4463-4a43-8928-3869f1c8d1b2
Hope we can solve this issue.
 
Thanks & Regards
Vidi

**Comment by viditrysatria** [comment]
Hi Mr.Romfrancois,

I found a bug where bar.close wasn't a number when making the bar. I fixed it by set the value into number.
in my suggestion The bar need to give some log error so i know what is wrong in generating bar in method callback.

Thank You.
