### ISSUE TITLE
Change resolution time is not working

### ISSUE THREAD

**Issue by caiqueacct** [tradingview/charting-library-tutorial#18]
Hi

Maybe I'm missing something but when I change the resolution time from 1D to 1W I get the following error on the chart:

Invalid symbol.

![Screen Shot 2021-02-07 at 09 10 27](https://user-images.githubusercontent.com/66717385/107153819-5e7e3280-6924-11eb-9ec4-6b6dd20beee4.png)

Any guidance?

Thanks

**Comment by timocov** [comment]
I think `ticker: symbolItem.full_name,` is missed in https://github.com/tradingview/charting-library-tutorial/blob/ea1d817abbaf65cd2a4fcc07b0199f4e6209671c/src/datafeed.js#L105-L118. I'll fix it soon. Thanks!
