### ISSUE TITLE
Tutorial not started because index.html contains error

### ISSUE THREAD

**Issue by SavosRU** [tradingview/charting-library-tutorial#19]
In the index.html we can see:
**src="charting_library_clonned_data/charting_library/charting_library.js">**

BUT!
On the way we can found only **charting_library.min.js**

So index.html looks as clean white screen. No chart etc...
After manually renamed file _charting_library.min.js_ to _charting_library.js_ - al works fine!
All the same after manually edit source in the _index.html_

Please - make one of these steps so project stay works correctly without users action!
thanks!

**Comment by timocov** [comment]
> On the way we can found only charting_library.min.js

This is because outdated version of charting library. The latest one includes `charting_library.js` https://github.com/tradingview/charting_library/blob/master/charting_library/charting_library.js.
