### ISSUE TITLE
Not seeing chart in tutorial Deployed Preview

### ISSUE THREAD

**Issue by bitcoinappdev** [tradingview/charting-library-tutorial#21]
The "Getting Started" tutorial page has anchor text "Deployed Preview" which links to this page:

https://charting-library.tradingview.com/tutorial/index.html

and there doesn't appear to be a chart there - that is, there are no candlesticks on the chart. 

Isn't there supposed to be a chart displayed? If so, any idea why it's not showing and how to fix it?

**Comment by timocov** [comment]
Ah, it needs to be updated according to the latest API. We'll fix it soon.

**Comment by timocov** [comment]
Now it should be fine. Thanks for observation!
