### ISSUE TITLE
  getBars: async (symbolInfo, resolution, from, to, onHistoryCallback, onErrorCallback, firstDataRequest)

### ISSUE THREAD

**Issue by fogsy** [tradingview/charting-library-tutorial#22]
hey timocov I see you committed some updates 5 days ago there is something missing to where following the steps to implement the chart doesnt work tracking it down onHistoryCallback was undefined. Something is a miss either the functions are not in correct order or one of the functions/values are not being passed I wanted to report the issue Im back using the code pre cmmit.

**Comment by timocov** [comment]
@fogsy not too sure that understand what you mean. Can you please describe a little bit more what problem you have?

**Comment by arezoo88** [comment]
@timocov 
hi ,i have this problem too...in console ..i get this error:
TypeError: "onHistoryCallback is not a function"

**Comment by arezoo88** [comment]
![Screenshot_2021-04-26_10-13-40](https://user-images.githubusercontent.com/26740974/116034575-c1a47900-a678-11eb-953b-8bfb4083f61c.png)

**Comment by timocov** [comment]
@arezoo88 @fogsy please make sure that you use the latest unstable (v19 at the time) charting library.

**Comment by esmaeilmirzaee** [comment]
> ![Screenshot_2021-04-26_10-13-40](https://user-images.githubusercontent.com/26740974/116034575-c1a47900-a678-11eb-953b-8bfb4083f61c.png)

Alter it like this
`getBars: async(symbolInfo, resolution, from, to, onHistoryCallback, onErrorCallback, firstDataRequest) => {...}`

**Comment by timocov** [comment]
See https://github.com/tradingview/charting_library/wiki/Breaking-Changes#version-19
