### ISSUE TITLE
Money Flow Index (MFI) indicator results are wrong than expected

### ISSUE THREAD

**Issue by dirname** [tradingview/charting-library-tutorial#23]
Hello, 

I cloned this repository according to the tutorial and tried to run the demo, but after I can see the chart display, I tried to use the *MFI* indicator, but the result was **not** what I expected. The value of MFI is fixed at `100`. When I check the preview website provided by [TradingView](https://charting-library.tradingview.com/tutorial/index.html), this issue also exists.

<img width="1920" alt="Screenshot 2021-04-22 220916" src="https://user-images.githubusercontent.com/18101258/115729030-a1926280-a3b7-11eb-94fd-f2e98c088070.png">

Please help me as much as possible to solve this problem, thanks in advance :smiley:

**Comment by ezhukovskiy** [comment]
This is a volume based indicator. You don't have volume.

**Comment by dirname** [comment]
> This is a volume based indicator. You don't have volume.

Thanks, I mistakenly provided complete market data for the default chart. Now I added a volume field in `getBars`, and I got the expected result. In the future, can you also provide the volume in the default chart?

**Comment by timocov** [comment]
> In the future, can you also provide the volume in the default chart?

If you open https://charting-library.tradingview.com/ (not tutorial) you can see the volume there. In the tutorial we rely on the datafeed thus if datafeed doesn't provide volume, we can't generate it ourselves.
