### ISSUE TITLE
onHistoryCallback is not a function

### ISSUE THREAD

**Issue by arezoo88** [tradingview/charting-library-tutorial#24]
i get this error:
[getBars]: Get error TypeError: "onHistoryCallback is not a function"

**Comment by eugene-korobko** [comment]
Please pay your attention to breaking change on the latest release

`getBars(symbolInfo, resolution, periodParams, onHistoryCallback, onErrorCallback)`

and make sure your function has the same signature

**Comment by timocov** [comment]
And make sure that you're on the latest version of the library. This tutorial is adapted to work with the latest unstable version of the charting library. If you need some previous version, please use git history.
