### ISSUE TITLE
use csv file.

### ISSUE THREAD

**Issue by arezoo88** [tradingview/charting-library-tutorial#25]
How can i use csv file as data in chart?

**Comment by eugene-korobko** [comment]
Hello!

Could you please clarify how do you see the data workflow?

**Comment by arezoo88** [comment]
can you connect to my anydesk?

**Comment by praveenbm5** [comment]
May be an example demonstrating how we can use a OHLCV csv file with the charting_library will make it easy for many of us.

**Comment by c0tt0nc4ndyta** [comment]
did anyone able to plot OHLCV csv data to trading view?
