### ISSUE TITLE
charting_library.js  404 Not Found - after installation

### ISSUE THREAD

**Issue by mohit2** [tradingview/charting-library-tutorial#26]
After following all steps , getting error 

Request URL: http://localhost:5000/charting_library_clonned_data/charting_library/charting_library.js
Request Method: GET
Status Code: 404 Not Found

In folder after installation , can see  charting_library.min.js instead of  charting_library.s

**Comment by timocov** [comment]
What version of charting library do you use? Please update to the latest stable or unstable.
