### ISSUE TITLE
Live + updateFrequency datafeed?

### ISSUE THREAD

**Issue by neobie** [tradingview/charting-library-tutorial#41]
Possible to implement live data (socket io) + data refresh with updateFrequency param (traditional way)?
This is to avoid  data out of sync in case user Internet connection is disconnect and reconnect later, and some data in between is not getting updated in Live Chart.

**Comment by timocov** [comment]
@neobie you can do whatever you want to do in your application. This tutorial is just to show you how to connect real-world realtime data to the charting library.
