### ISSUE TITLE
Error with custom ticker with interval 1S

### ISSUE THREAD

**Issue by Viktor19931** [tradingview/charting-library-tutorial#53]
I could not configure ticker for bar interval 1S.

read doc few times and still could not resolve it. Please see screenshots.
<img width="556" alt="Screenshot 2021-12-23 at 01 51 09" src="https://user-images.githubusercontent.com/29923015/147167682-7abe59c4-6668-4a72-8dde-6e16e99f4824.png">
<img width="540" alt="Screenshot 2021-12-23 at 01 51 15" src="https://user-images.githubusercontent.com/29923015/147167683-e4072828-b699-4ad7-b62d-7b61ff36f476.png">
<img width="493" alt="Screenshot 2021-12-23 at 01 51 25" src="https://user-images.githubusercontent.com/29923015/147167684-449fef39-329f-407b-873a-f4d366f205c3.png">

Thanks!

**Comment by romfrancois** [comment]
Hi @Viktor19931,

What's your server configuration?
I believe you could find some answers [here](https://github.com/tradingview/charting_library/wiki/Resolution) and [here](https://github.com/tradingview/charting_library/wiki/JS-Api#onreadycallback).

**Comment by Viktor19931** [comment]
I added to symbol resolution as ['1S'] and server supports just seconds bar for now

**Comment by Viktor19931** [comment]
@romfrancois 
I used configureData on chart ready
```const configurationData = {
  supports_search: false,
  supports_group_request: false,
  supported_resolutions: ['1S' as ResolutionString],
  supports_marks: false,
  supports_timescale_marks: false,
};
```
