### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by epezon** [tradingview/charting-library-tutorial#58]
Hi there,
I am trying to implement streaming with polygon.io websocket. I have configured the websocket in the streaming.js file but the chart seems to try to connect to wrong address:
![image](https://user-images.githubusercontent.com/54973181/156129849-410dec5c-a038-423e-8b90-a8b3226c4cff.png)

This is my configuration from the streaming.js file:
const socket = io('wss://delayed.polygon.io/stocks');

The index.html contains the socket.io script :
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.7.2/socket.io.js"></script>

Any idea how to fix this? The chart works fine otherwise.

**Comment by timocov** [comment]
How this query is related to the tutorial?

**Comment by epezon** [comment]
I am using the tutorial files as a base. Since I don´t want to use it for cryptos but stocks, I was wondering if you could help me with how to change the websocket address.

**Comment by timocov** [comment]
Well, in this case I think you need to contact the API provider or ask the question on stackoverflow.

**Comment by epezon** [comment]
Ok, will do that.
